### ISSUE TITLE
Git tag

### ISSUE THREAD

**Issue by ghost** [opetch/terraform-aws-cli-resource#5]
Could you add a tag of current working version of your module?
I would like to use it directly from github.

Thanks.

**Comment by opetch** [comment]
Hi there, we use (at my current client) this module directly from GitHub, we do so like this...
`source = "github.com/opetch/terraform-aws-cli-resource?ref=b1015ef"`
using the git sha to identify commit, hopefully this will suffice for your needs? Can I just confirm what it is you're asking for? Is it....

1. A tag that would identify the latest working version, effectively a moving target, would require removing and re-tagging after further updates.
2.  A version number tag on each commit/new version.

I'd like to avoid 1 as that is not too dissimilar from a snapshot, whereby a consumer could end up taking an update without their codebase changing. Effectively having both a broken and working build from the same version of their code (because the dependency has changed). I'd also like to avoid 2 as I consider the git sha to be a good enough unique identifier, albeit difficult to tell which version is newer from looking at the sha alone.

**Comment by opetch** [comment]
I'm closing this issue given I have created https://github.com/opetch/terraform-aws-cli-resource/issues/6 happy to accept a PR if someone is looking to contribute. It's fairly involved so may never happen but the Issue does document how I would like to ideally approach versioning.
